package it.polimi.se2018.utils;

public enum Move {
    END_TURN,
    DRAFT_DICE_FROM_DRAFTPOOL,
    PLACE_DICE_ON_WINDOWPATTERN,
    USE_TOOLCARD,
    INCREMENT_DRAFTED_DICE,
    DECREMENT_DRAFTED_DICE,
    CHANGE_DRAFTED_DICE_VALUE,
    CHOOSE_DICE_FROM_TRACK,
    MOVE_DICE,
    JOIN_GAME,
    BACK_GAME,
    LEAVE,
    NAVIGATE_INFOS //just for CLI
}
